using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SecureCheck.Core.Entities;
using SecureCheck.Core.Interfaces;

namespace SecureCheck.Infrastructure.Services;

public class AdmitCardPdfService : IAdmitCardService
{
    private readonly string _outputFolder;

    public AdmitCardPdfService(string outputFolder = "AdmitCards")
    {
        _outputFolder = Path.GetFullPath(outputFolder);
        Directory.CreateDirectory(_outputFolder);
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public Task<string> GenerateAdmitCardAsync(Student student, ExamRegistration registration, byte[] qrCodePng)
    {
        var filePath = Path.Combine(_outputFolder, $"{registration.Id}.pdf");

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A5);
                page.Margin(24);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text("ADMIT CARD").FontSize(18).Bold();

                page.Content().Column(col =>
                {
                    col.Item().Text($"Name: {student.FullName}");
                    col.Item().Text($"Roll Number: {student.RollNumber}");
                    col.Item().Text($"Subject: {student.Subject}");
                    col.Item().Text($"Exam: {registration.ExamName}");
                    col.Item().Text($"Date: {registration.ExamDateUtc:dd MMM yyyy}");
                    col.Item().Text($"Seat: {registration.SeatNumber}");

                    col.Item().PaddingTop(16).Image(qrCodePng);
                    col.Item().Text("Scan to verify identity").FontSize(9).Italic();
                });

                page.Footer().AlignCenter().Text("Generated by SecureCheck");
            });
        }).GeneratePdf(filePath);

        registration.AdmitCardPdfPath = filePath;
        return Task.FromResult(filePath);
    }
}
